# This configuration file was copy and pasted 

tasks:
  - init: |
      docker-compose -f docker-compose-dev.yml pull
  - command: |
      docker-compose -f docker-compose-dev.yml up

ports:
  - port: 3000
    onOpen: open-browser
  - port: 2080
    onOpen: open-browser
  - port: 1080
    onOpen: open-browser
#   - port: 9200
#     onOpen: open-preview
#   - port: 9300
#     onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
