# This configuration file was mainly inspired by ./doc/SETUP_DEVELOPMENT_DOCKER.md
tasks:
  - name: Docker
    init: |
      # init docker containers
      docker-compose -f docker-compose-dev.yml pull
      docker-compose -f docker-compose-dev.yml up -d mariadb
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle install
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle exec rake foodsoft:setup_development_docker
    command: |
      # start docker containers
      docker-compose -f docker-compose-dev.yml up
      
  - name: Rails
    before: |
      sudo apt-get install -y libmagic-dev
      # install correct ruby+tools versions
      printf "rvm_gems_path=/home/gitpod/.rvm\n" > ~/.rvmrc
      rvm reinstall $(cat .ruby-version)
      rvm use $(cat .ruby-version) --default 
      gem install bundler
      printf "rvm_gems_path=/workspace/.rvm" > ~/.rvmrc
    init: |
      bundle install

ports:
  - port: 3000
    onOpen: open-preview
  - port: 2080
    onOpen: notify
  - port: 1080
    onOpen: notify

vscode:
  extensions:
    - ms-azuretools.vscode-docker
