# This configuration file was mainly inspired by ./doc/SETUP_DEVELOPMENT_DOCKER.md

tasks:
  - init: |
      docker-compose -f docker-compose-dev.yml pull
      docker-compose -f docker-compose-dev.yml up -d mariadb
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle install
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle exec rake foodsoft:setup_development_docker
      touch /workspace/prebuild.done
  - command: |
      until [ -f /workspace/prebuild.done ]
      do
          echo "waiting for prebuild.done file..."
          sleep 1
      done
      echo "prebuild.done file found"
      docker-compose -f docker-compose-dev.yml up


ports:
  - port: 3000
    onOpen: open-preview
  - port: 2080
    onOpen: notify
  - port: 1080
    onOpen: notify

vscode:
  extensions:
    - ms-azuretools.vscode-docker
