# This configuration file was copy and pasted 

tasks:
  - init: |
      docker-compose -f docker-compose-dev.yml pull
  - command: |
      docker-compose -f docker-compose-dev.yml up

# ports:
#   - port: 5000
#     onOpen: ignore
#   - port: 5601
#     onOpen: open-browser
#   - port: 9200
#     onOpen: open-preview
#   - port: 9300
#     onOpen: ignore
#   - port: 9600
#     onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
