# This configuration file was copy and pasted 

tasks:
  - init: |
      docker-compose -f docker-compose-dev.yml pull
      docker-compose -f docker-compose-dev.yml up -d mariadb
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle install
      docker-compose -f docker-compose-dev.yml run --rm foodsoft bundle exec rake foodsoft:setup_development_docker
      docker-compose -f docker-compose-dev.yml up


ports:
  - port: 3000
    onOpen: open-preview
  - port: 2080
    onOpen: open-preview
  - port: 1080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
