inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Gemspec/OrderedDependencies:
  Exclude:
    - 'plugins/*/*.gemspec'
