inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  # Exclude:
  #   - 'db/**/*'
  #   - 'bin/*'

Gemspec/OrderedDependencies:
  Exclude:
    - 'plugins/*/*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/foodsoft.rake'
